apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluxinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: flux-chart
      version: '3.12.3'
      sourceRef:
        kind: GitRepository
        name: helmpods
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
