apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helmpod
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./
      version: '4.0'
      sourceRef:
        kind: GitRepository
        name: helmpod
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2
