apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-helm-release
  namespace: my-namespace
spec:
  interval: 5m  # Sync interval (optional)
  chart:
    repository: https://github.com/venkallex/flux.git   # URL of the Helm chart repository
    name: flux-chart                           # Name of the Helm chart
    version: 1.2.3                           # Version of the Helm chart
  values:
    replicaCount: 3                          # Custom values for the Helm chart
    serviceName: my-service                  # Another custom value
