apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deploy-kube-resources-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes-resources
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system 
