apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: helmpod
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/venkallex/flux.git
  ref:
    branch: main
                         
